apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: a-to-b
  namespace: namespace-net-pol
spec:
  podSelector:
    matchLabels:
      app: a
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: b
    ingress:
      - to:
          - podSelector:
              matchLabels:
                app: b
    egress:
      - to:
          - podSelector:
              matchLabels:
                app: b
