apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: a-to-b
  namespace: namespace-pod
spec:
  podSelector:
    matchLabels:
      app: a
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: b
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: b
